{{- if .Values.templates.settlementWindow -}}

apiVersion: mojaloop.io/v1
kind: MojaloopReport
metadata:
  name: {{ printf "%s-%s" .Release.Name "settlement-window" | trimPrefix "-" }}
  {{ include "common.annotations" . | nindent 2 }}
spec:
  permission: report-settlement-window
  endpoint:
    path: /settlementWindow
  queries:
    - name: report
      query: |
        SELECT sq.*, swOpen.createdDate AS windowOpen, swClose.createdDate as windowClose
        FROM
          (
              SELECT
                  qp.fspId,
                  sw.settlementWindowId,
                  swsc.settlementWindowStateId AS state,
                  COUNT(qp.amount) AS numTransactions,
                  SUM(qp.amount) AS netPosition
              FROM
                  central_ledger.settlementWindow AS sw
              LEFT JOIN
                   central_ledger.transferFulfilment AS tf
                   ON tf.settlementWindowId = sw.settlementWindowId
              LEFT JOIN
                   central_ledger.transactionReference AS tr
                   ON tf.transferId = tr.transactionReferenceId
              INNER JOIN
                   central_ledger.transferParticipant AS tp
                   ON tp.transferId = tf.transferId
              INNER JOIN
                   central_ledger.transferParticipantRoleType AS trpt
                   ON trpt.transferParticipantRoleTypeId = tp.transferParticipantRoleTypeId
              INNER JOIN
                   central_ledger.settlementWindowStateChange AS swsc
                   ON swsc.settlementWindowStateChangeId = sw.currentStateChangeId
              LEFT JOIN
                   central_ledger.quoteParty AS qp
                   ON qp.quoteId = tr.quoteId AND qp.transferParticipantRoleTypeId = tp.transferParticipantRoleTypeId
              GROUP BY qp.fspId, sw.settlementWindowId
          ) AS sq
        INNER JOIN
          central_ledger.settlementWindowStateChange AS swOpen
          ON swOpen.settlementWindowId = sq.settlementWindowId
        LEFT OUTER JOIN
          central_ledger.settlementWindowStateChange AS swClose
          ON swClose.settlementWindowId = sq.settlementWindowId AND swClose.settlementWindowStateId = 'CLOSED'
        WHERE
        swOpen.settlementWindowStateId = 'OPEN'
  template: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <style>
            table {
                font-family: arial, sans-serif;
                border-collapse: collapse;
                width: 100%;
                display: block;
                overflow-x: auto;
                white-space: nowrap;
            }

            th {
            //            border: 1px solid #efefef;
                text-align: left;
                padding: 0 8px;
            }

            td {
    //            border: 1px solid #efefef;
                padding: 8px;
            }

            tr:nth-child(even) {
    //            background-color: #efefef;
            }

            td > span {
                font-weight: bold;
            }
        </style>
        <title>FSP Settlement Report</title>
    </head>
    <body>

    <%
        const formatAmount = (amount) => parseFloat(amount).toLocaleString('en-US');
    %>

    <table>
            <tr>
                <td>fspId</td>
                <td>settlementWindowId</td>
                <td>state</td>
                <td>numTransactions</td>
                <td>netPosition</td>
                <td>windowOpen</td>
            </tr>
            <% for(let e of report) { %>
                <tr>
                    <td><%= e.fspId %></td>
                    <td><%= e.settlementWindowId %></td>
                    <td><%= e.state %></td>
                    <td><%= e.numTransactions %></td>
                    <td><%= e.netPosition %></td>
                    <td><%= e.windowOpen.toISOString() %></td>
                </tr>
            <% } %>
        </table>
    </body>
    </html>

{{- end }}
