apiVersion: mojaloop.io/v1
kind: MojaloopReport
metadata:
  name: report-transaction-detail
spec:
  endpoint:
    params:
      - name: transferId
        required: true
    path: /report-transaction-detail
  permission: transferApi
  queries:
    - name: transfers
      query: "select\n\tqp1.fspId as endPayerFsp,\n  payerpit.name as payerIdentifierTypeName,\n\tqp1.partyIdentifierValue as payerIdentifierValue,\n  qp1.partyName as payerName,\n\tqp2.fspId as endPayeeFsp,\n  payeepit.name as payeeIdentifierTypeName,\n\tqp2.partyIdentifierValue as payeeIdentifierValue,\n  qp2.partyName as payeeName,\n  q.quoteId as quoteId,\n  q.transactionReferenceId as transactionReferenceId,\n  fqct.conversionId as conversionId,\n  fqct.expirationDate as conversionExpiry,\n  ft.commitRequestId as commitRequestId,\n  transfer.expirationDate as transferExpiry,\n  qr.payeeFspFeeAmount as payeeFspFeeAmount,\n  qr.payeeFspCommissionAmount as payeeFspCommissionAmount,\n  fqrct.sourceAmount as conversionTermsSourceAmount,\n  fqrct.targetAmount as conversionTermsTargetAmount,\n  fxtsc.transferStateId as fxTransferState,\n    `transfer`.*,\n    ft.*,\n    `transfer`.`currencyId` as `currency`,\n    `tp1`.`amount` as `payerAmount`,\n    `da`.`participantId` as `payerParticipantId`,\n    `da`.`name` as `payerFsp`,\n    `tp2`.`amount` as `payeeAmount`,\n    `ca`.`participantId` as `payeeParticipantId`,\n    `ca`.`name` as `payeeFsp`,\n    `fda`.`name` as `fxpName`,\n    `tsc`.`transferStateId` as `transferState`,\n    `tsc`.`reason` as `reason`,\n    `tsc`.`createdDate` as `completedTimestamp`\nfrom\n    `transfer`\ninner join `transferParticipant` as `tp1` on\n    `tp1`.`transferId` = `transfer`.`transferId`\ninner join `transferParticipantRoleType` as `tprt1` on\n    `tprt1`.`transferParticipantRoleTypeId` = `tp1`.`transferParticipantRoleTypeId`\ninner join `participant` as `da` on\n    `da`.`participantId` = `tp1`.`participantId`\ninner join `transferParticipant` as `tp2` on\n    `tp2`.`transferId` = `transfer`.`transferId`\ninner join `transferParticipantRoleType` as `tprt2` on\n    `tprt2`.`transferParticipantRoleTypeId` = `tp2`.`transferParticipantRoleTypeId`\ninner join `participant` as `ca` on\n    `ca`.`participantId` = `tp2`.`participantId`\ninner join (select tsc1.transferId, max(tsc1.transferStateChangeId) as maxTransferStateChangeId from `transferStateChange` as `tsc1` group by tsc1.transferId) as ts on\n    `ts`.`transferId` = `transfer`.`transferId`\ninner join `transferStateChange` as `tsc` on\n    `tsc`.`transferStateChangeId` = `ts`.`maxTransferStateChangeId`\ninner join `fxTransfer` as ft on\n    ft.determiningTransferId = transfer.transferId\ninner join (select fxtsc1.commitRequestId, max(fxtsc1.fxTransferStateChangeId) as maxFxTransferStateChangeId from `fxTransferStateChange` as `fxtsc1` group by fxtsc1.commitRequestId) as fxts on\n    `fxts`.`commitRequestId` = `ft`.`commitRequestId`\ninner join `transferStateChange` as `fxtsc` on\n    `fxtsc`.`transferStateChangeId` = `fxts`.`maxFxTransferStateChangeId`\ninner join `fxTransferParticipant` as `ftp1` on\n    `ftp1`.`commitRequestId` = `ft`.`commitRequestId` and `ftp1`.fxParticipantCurrencyTypeId  = 1\ninner join `transferParticipantRoleType` as `ftprt1` on\n    `ftprt1`.`transferParticipantRoleTypeId` = `ftp1`.`transferParticipantRoleTypeId`\ninner join `participant` as `fda` on\n    `fda`.`participantId` = `ftp1`.`participantId`\ninner join fxQuoteConversionTerms fqct on\n\tfqct.conversionId = `ft`.`commitRequestId`\ninner join fxQuoteResponseConversionTerms fqrct on\n\tfqrct.conversionId = `ft`.`commitRequestId`\ninner join quote q on\n    q.transactionReferenceId = transfer.transferId\ninner join quoteParty qp1 on\n    qp1.quoteId = q.quoteId and qp1.partyTypeId = tprt1.transferParticipantRoleTypeId\ninner join quoteParty qp2 on\n    qp2.quoteId = q.quoteId and qp2.partyTypeId = tprt2.transferParticipantRoleTypeId\ninner join partyIdentifierType payerpit on\n    payerpit.partyIdentifierTypeId = qp1.partyIdentifierTypeId\ninner join partyIdentifierType payeepit on\n    payeepit.partyIdentifierTypeId = qp2.partyIdentifierTypeId\ninner join fxCharge fxc on\n    fxc.conversionId = fqrct.conversionId\ninner join quoteResponse qr on\n    qr.quoteId = q.quoteId\nwhere\n    `tprt1`.`name` = 'PAYER_DFSP'\n    and `tprt2`.`name` = 'PAYEE_DFSP'\n    and `ftprt1`.`name` = 'COUNTER_PARTY_FSP'\n    and `transfer`.`transferId` = :transferId;\n"
    - name: fxCharges
      query: "select DISTINCT fxc.fxChargeId, fxc.* from fxCharge join fxTransfer as ft on\n  ft.determiningTransferId = :transferId\njoin fxQuoteResponseConversionTerms fqrct on\n\tfqrct.conversionId = ft.commitRequestId\njoin fxCharge as fxc on\n  fxc.conversionId = fqrct.conversionId\nwhere\n  ft.determiningTransferId = :transferId\n"
  template: |
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>DRPP Transaction Report</title>
        <style>
            body {
                font-family: 'Arial', sans-serif;
                background-color: #f5f5f5;
                margin: 0;
                padding: 20px;
                color: #333;
            }

            .container {
                max-width: 100%;
                margin: 0 auto;
                background-color: #fff;
                padding: 20px;
                box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            }

            .header {
                display: flex;
                justify-content: space-between;
                align-items: center;
                border-bottom: 2px solid #00447c;
                padding-bottom: 10px;
            }

            .header h1 {
                margin: 0;
                color: #00447c;
                font-size: 24px;
            }

            .header img {
                max-height: 50px;
            }

            .summary {
                margin-top: 20px;
                padding: 15px;
                background-color: #e9f3fa;
                border-left: 6px solid #00447c;
                border-radius: 5px;
                box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
                max-width: 500px;
            }

            .summary p {
                margin: 5px 0;
                font-weight: bold;
            }

            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }

            table, th, td {
                border: 1px solid #ddd;
            }

            th {
                background-color: #00447c;
                color: #fff;
                padding: 10px;
                font-size: 1.0em;
            }

            td {
                line-height: 1.6;
                padding: 10px;
                text-align: left;
                font-size: 0.9em;
            }

            tr:nth-child(even) {
                background-color: #f2f2f2;
            }

            .smallFont {
                font-size: 0.7em;
            }

            .thStyle {
                background-color: #00447c;
                color: #fff;
                padding: 10px;
                font-size: 1.0em;
            }

            .footer {
                margin-top: 20px;
                text-align: center;
                font-size: 0.9em;
                color: #666;
            }

            .footer p {
                margin: 5px 0;
            }
        </style>
    </head>

    <%
      const transferId = transfers[0]?.transferId;
      const submittedAt = transfers[0]?.createdDate.toUTCString();
      const sourceAmount = transfers[0]?.sourceAmount;
      const sourceCurrency = transfers[0]?.sourceCurrency;
      const targetAmount = transfers[0]?.targetAmount;
      const targetCurrency = transfers[0]?.targetCurrency;
      const transferState = transfers[0]?.transferState;
      const transferExpiry = transfers[0]?.transferExpiry.toUTCString();
      const conversionExpiry = transfers[0]?.conversionExpiry.toUTCString();
      const quoteId = transfers[0]?.quoteId;
      const transactionReferenceId = transfers[0]?.transactionReferenceId;
      const commitRequestId = transfers[0]?.commitRequestId;
      const conversionId = transfers[0]?.conversionId;

      const fxpName = transfers[0]?.fxpName;
      const fxTransferState = transfers[0]?.fxTransferState;

      const payerIdentifierValue = transfers[0]?.payerIdentifierValue;
      const payerIdentifierTypeName = transfers[0]?.payerIdentifierTypeName;
      const payerName = transfers[0]?.payerName;
      const payerProxyName = transfers[0]?.payerFsp;
      const payerFspName = transfers[0]?.endPayerFsp;

      const payeeIdentifierValue = transfers[0]?.payeeIdentifierValue;
      const payeeIdentifierTypeName = transfers[0]?.payeeIdentifierTypeName;
      const payeeName = transfers[0]?.payeeName;
      const payeeProxyName = transfers[0]?.payeeFsp;
      const payeeFspName = transfers[0]?.endPayeeFsp;
      const payeeFspFeeAmount = transfers[0]?.payeeFspFeeAmount;
      const payeeFspCommissionAmount = transfers[0]?.payeeFspCommissionAmount;

      const conversionTermsSourceAmount = transfers[0]?.conversionTermsSourceAmount;
      const conversionTermsTargetAmount = transfers[0]?.conversionTermsTargetAmount;

      const sourceAmountConversionCharges = fxCharges.reduce((n, {sourceAmount}) => n + sourceAmount, 0);
      const targetAmountConversionCharges = fxCharges.reduce((n, {targetAmount}) => n + targetAmount, 0);

      const exchangeRate = (sourceAmount - sourceAmountConversionCharges) / (targetAmount - targetAmountConversionCharges);

      const conversionSettlementBatchId = null;
    %>
    <body>
        <div class="container">
            <div class="header">
                <h1>DRPP Transaction Detail Report</h1>
                <img src="https://comesabusinesscouncil.org/wp-content/uploads/2022/10/cropped-cropped-cropped-cbc_logo-1.jpg" alt="Logo">
            </div>

            <div class="summary">
                <p>For Regional Hub</p>
                <p>Transfer ID: <%= transferId %></p>
                <p>State: <%= transferState %></p>
            </div>
            <div>
              <br /><a href="report-transaction?format=html">View all Transactions</a>
            </div>
            <table>
                <tbody>
                  <tr>
                    <td>Transfer Description</td>
                    <td>
                      At <i>"<%=submittedAt%>"</i>" <b><%=sourceAmount%> <%=sourceCurrency%></b> was transferred from "<%=payerFspName%>" to "<%=payeeFspName%>" who received <b><%=targetAmount%> <%=targetCurrency%></b>.
                      <br />"<%=payerFspName%>" <%= payerFspName==payerProxyName ? `[was represented by ${payerProxyName} who]` : '' %> was debited by <%=sourceAmount%> <%=sourceCurrency%>.
                      <br />"<%=payeeFspName%>" <%= payeeFspName==payeeProxyName ? `[was represented by ${payeeProxyName} who]` : '' %> was credited by <%=targetAmount%> <%=targetCurrency%>.
                      <br />Conversion was performed by <%=fxpName%>.
                    </td>
                </tr>
                <tr>
                  <td>Payer Details</td>
                  <td>
                    <%= payerIdentifierValue %> <%= payerIdentifierTypeName %> at <%= payerFspName %>
                    <%= payerName %>
                    Supporting these currencies: <%= sourceCurrency %>
                  </td>
                </tr>
                <tr>
                  <td>Payee Details</td>
                  <td>
                    <%= payeeIdentifierValue %> <%= payeeIdentifierTypeName %> at <%= payeeFspName %>
                    <%= payeeName %>
                    Supporting these currencies: <%= targetCurrency %>
                  </td>
                </tr>
                <tr>
                  <td>Transfer Terms</td>
                  <td>
                    Transfer Amount <b><%=sourceAmount%> <%=sourceCurrency%>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    Payee Receive Amount <%=targetAmount%> <%=targetCurrency%>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    Payee DFSP Fee <%= payeeFspFeeAmount || 0 %> <%=targetCurrency%>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    Payee DFSP Commission <%= payeeFspCommissionAmount || 0 %> <%=targetCurrency%>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    Transfer Expiry <%= transferExpiry %>
                  </td>
                </tr>
                <tr>
                  <td>Currency Conversions Terms</td>
                  <td>
                    Send Amount <%= conversionTermsSourceAmount %> <%= sourceCurrency %>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    Receive Amount <%= conversionTermsTargetAmount %> <%= targetCurrency %>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    Conversion Charge Amount <%= sourceAmountConversionCharges %> <%= sourceCurrency %>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    Conversion Charge Amount <%= targetAmountConversionCharges %> <%= targetCurrency %>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    Exchange Rate <%= exchangeRate %>
                    (<%= sourceAmount %> - <%= sourceAmountConversionCharges %>/<%= targetAmount %> - <%= targetAmountConversionCharges %>)
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    Conversion Expiry <%= conversionExpiry %>
                  </td>
                </tr>
                <tr>
                  <td>Conversion Settlement Batch</td>
                  <td>
                    <%= conversionSettlementBatchId || 'Not yet settled' %>
                  </td>
                </tr>
                <tr>
                  <td>Technical Details</td>
                  <td>
                    Transaction Id <%= transactionReferenceId %>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    Transfer Id <%= transferId %>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    Quote Id <%= quoteId %>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    Conversion Id <%= commitRequestId %>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    Conversion Quote Id <%= conversionId %>
                  </td>
                </tr>
                <tr>
                  <td></td>
                  <td>
                    Conversion State <%= fxTransferState %>
                  </td>
                </tr>
            </table>

            <div class="footer">
                <p>Generated on: test</p>
            </div>
        </div>

    </body>
    </html>
